import { Car } from "@/models/car.model";

export const cars: Car[] = [
  {
    id: "1",
    slug: "obsidian-gt",
    name: "Obsidian GT",
    brand: "Aurelia",
    year: 2024,
    bodyType: "Coupe",
    pricePerDay: 1600,
    image: "obsidian-gt",
    featured: true,
    specs: [
      { label: "Power", value: "620 hp" },
      { label: "0-60", value: "2.9s" },
      { label: "Drive", value: "AWD" },
      { label: "Interior", value: "Onyx leather" },
      { label: "Range", value: "410 mi" },
      { label: "Audio", value: "16 speaker studio" },
    ],
  },
  {
    id: "2",
    slug: "crimson-eclipse",
    name: "Crimson Eclipse",
    brand: "Velvetis",
    year: 2023,
    bodyType: "Grand tourer",
    pricePerDay: 1850,
    image: "crimson-eclipse",
    featured: true,
    specs: [
      { label: "Power", value: "680 hp" },
      { label: "0-60", value: "3.1s" },
      { label: "Drive", value: "RWD" },
      { label: "Interior", value: "Bordeaux alcantara" },
      { label: "Range", value: "385 mi" },
      { label: "Audio", value: "18 speaker concert" },
    ],
  },
  {
    id: "3",
    slug: "onyx-sabre",
    name: "Onyx Sabre",
    brand: "Nocturne",
    year: 2024,
    bodyType: "Sedan",
    pricePerDay: 1200,
    image: "onyx-sabre",
    featured: false,
    specs: [
      { label: "Power", value: "540 hp" },
      { label: "0-60", value: "3.7s" },
      { label: "Drive", value: "AWD" },
      { label: "Interior", value: "Midnight suede" },
      { label: "Range", value: "440 mi" },
      { label: "Audio", value: "14 speaker studio" },
    ],
  },
  {
    id: "4",
    slug: "velour-phantom",
    name: "Velour Phantom",
    brand: "Maison Valtor",
    year: 2022,
    bodyType: "SUV",
    pricePerDay: 980,
    image: "velour-phantom",
    featured: false,
    specs: [
      { label: "Power", value: "480 hp" },
      { label: "0-60", value: "4.6s" },
      { label: "Drive", value: "AWD" },
      { label: "Interior", value: "Velvet noir" },
      { label: "Range", value: "470 mi" },
      { label: "Audio", value: "12 speaker suite" },
    ],
  },
  {
    id: "5",
    slug: "ember-revenant",
    name: "Ember Revenant",
    brand: "Solenne",
    year: 2024,
    bodyType: "Roadster",
    pricePerDay: 2100,
    image: "ember-revenant",
    featured: true,
    specs: [
      { label: "Power", value: "710 hp" },
      { label: "0-60", value: "2.7s" },
      { label: "Drive", value: "AWD" },
      { label: "Interior", value: "Crimson leather" },
      { label: "Range", value: "360 mi" },
      { label: "Audio", value: "18 speaker studio" },
    ],
  },
  {
    id: "6",
    slug: "midnight-regal",
    name: "Midnight Regal",
    brand: "Imperium",
    year: 2023,
    bodyType: "Limousine",
    pricePerDay: 2400,
    image: "midnight-regal",
    featured: false,
    specs: [
      { label: "Power", value: "590 hp" },
      { label: "0-60", value: "4.3s" },
      { label: "Drive", value: "RWD" },
      { label: "Interior", value: "Obsidian lounge" },
      { label: "Range", value: "500 mi" },
      { label: "Audio", value: "22 speaker suite" },
    ],
  },
];

export const carController = {
  getAll: async (): Promise<Car[]> => cars,
  getFeatured: async (): Promise<Car[]> => cars.filter((car) => car.featured),
  getBySlug: async (slug: string): Promise<Car | null> =>
    cars.find((car) => car.slug === slug) ?? null,
};
